# coding: utf-8

Company.delete_all
Company.create!([
  {
    id: 1,
    status: 'public',
    name: 'サンプル畳店1',
    busyness: 'lowest',
    zip: '123-4567',
    prefecture: 'tokyo',
    address: '日野市南平1-10-306',
    make_count: 6,
    member_count: 2,
    body: 'これは本文です',
    tel: '090-1234-5678',
    email: 'user1@tatami.jp',
    password: 'password',
  }, {
    id: 2,
    status: 'public',
    name: 'サンプル畳店2',
    busyness: 'high',
    zip: '123-4567',
    prefecture: 'aichi',
    address: '名古屋市南平1-10-306',
    make_count: 12,
    member_count: 5,
    body: 'これは本文です',
    tel: '090-1234-5678',
    email: 'user2@tatami.jp',
    password: 'password',
  }, {
    id: 3,
    status: 'public',
    name: 'サンプル畳店3',
    busyness: 'normal',
    zip: '123-4567',
    prefecture: 'chiba',
    address: '千葉市美浜区1-10-306',
    make_count: 5,
    member_count: 1,
    body: 'これは本文です',
    tel: '090-1234-5678',
    email: 'user3@tatami.jp',
    password: 'password',
  } , {
    id: 4,
    status: 'public',
    name: 'サンプル畳店4',
    busyness: 'normal',
    zip: '123-4567',
    prefecture: 'chiba',
    address: '千葉市美浜区1-10-306',
    make_count: 5,
    member_count: 1,
    body: 'これは本文です',
    tel: '090-1234-5678',
    email: 'user4@tatami.jp',
    password: 'password',
  }, {
    id: 5,
    status: 'public',
    name: 'サンプル畳店5',
    busyness: 'normal',
    zip: '123-4567',
    prefecture: 'chiba',
    address: '千葉市美浜区1-10-306',
    make_count: 5,
    member_count: 1,
    body: 'これは本文です',
    tel: '090-1234-5678',
    email: 'user5@tatami.jp',
    password: 'password',
  }, {
    id: 6,
    status: 'private',
    name: 'サンプル畳店6',
    busyness: 'normal',
    zip: '123-4567',
    prefecture: 'chiba',
    address: '千葉市美浜区1-10-306',
    make_count: 5,
    member_count: 1,
    body: 'これは本文です',
    tel: '090-1234-5678',
    email: 'user6@tatami.jp',
    password: 'password',
  }, {
    id: 7,
    status: 'public',
    name: 'サンプル畳店7',
    busyness: 'normal',
    zip: '123-4567',
    prefecture: 'chiba',
    address: '千葉市美浜区1-10-306',
    make_count: 5,
    member_count: 1,
    body: 'これは本文です',
    tel: '090-1234-5678',
    email: 'user7@tatami.jp',
    password: 'password',
  }, {
    id: 8,
    status: 'public',
    name: 'サンプル畳店8',
    busyness: 'normal',
    zip: '123-4567',
    prefecture: 'chiba',
    address: '千葉市美浜区1-10-306',
    make_count: 5,
    member_count: 1,
    body: 'これは本文です',
    tel: '090-1234-5678',
    email: 'user8@tatami.jp',
    password: 'password',
  }, {
    id: 9,
    status: 'private',
    name: 'サンプル畳店9',
    busyness: 'normal',
    zip: '123-4567',
    prefecture: 'chiba',
    address: '千葉市美浜区1-10-306',
    make_count: 5,
    member_count: 1,
    body: 'これは本文です',
    tel: '090-1234-5678',
    email: 'user9@tatami.jp',
    password: 'password',
  }
])

Project.delete_all
Project.create!([
  {
    id: 1,
    source_company_id: 1,
    status: "public",
    name: "案件1",
    body: "案件1の本文です",
    kind_body: "案件1の畳表の種類",
    kind_edge: "案件1の畳縁の種類",
    need_amount: 200,
    deadline: Date.new(2016, 3, 20),
    estimated_sum: 30000,
  },{
    id: 2,
    source_company_id: 1,
    status: "private",
    name: "案件2",
    body: "案件2の本文です",
    kind_body: "案件2の畳表の種類",
    kind_edge: "案件2の畳縁の種類",
    need_amount: 100,
    deadline: Date.new(2016, 3, 20),
    estimated_sum: 30000,
  },{
    id: 3,
    source_company_id: 2,
    dest_company_id: 1,
    status: "public",
    name: "案件3",
    body: "案件3の本文です",
    kind_body: "案件3の畳表の種類",
    kind_edge: "案件3の畳縁の種類",
    need_amount: 10,
    deadline: Date.new(2016, 3, 20),
    estimated_sum: 30000,
  },{
    id: 4,
    source_company_id: 3,
    status: "public",
    name: "案件4",
    body: "案件4の本文です",
    kind_body: "案件4の畳表の種類",
    kind_edge: "案件4の畳縁の種類",
    need_amount: 20,
    deadline: Date.new(2016, 3, 20),
    estimated_sum: 30000,
  },{
    id: 5,
    source_company_id: 2,
    status: "public",
    name: "案件5",
    body: "案件5の本文です",
    kind_body: "案件5の畳表の種類",
    kind_edge: "案件5の畳縁の種類",
    need_amount: 20,
    deadline: Date.new(2016, 3, 20),
    estimated_sum: 30000,
  },{
    id: 6,
    source_company_id: 1,
    dest_company_id: 2,
    status: "public",
    name: "案件6",
    body: "案件6の本文です",
    kind_body: "案件6の畳表の種類",
    kind_edge: "案件6の畳縁の種類",
    need_amount: 20,
    deadline: Date.new(2016, 3, 20),
    estimated_sum: 30000,
  },{
    id: 7,
    source_company_id: 2,
    status: "public",
    name: "案件7",
    body: "案件7の本文です",
    kind_body: "案件7の畳表の種類",
    kind_edge: "案件7の畳縁の種類",
    need_amount: 20,
    deadline: Date.new(2016, 3, 20),
    estimated_sum: 30000,
  },{
    id: 8,
    source_company_id: 1,
    status: "public",
    name: "案件8",
    body: "案件8の本文です",
    kind_body: "案件8の畳表の種類",
    kind_edge: "案件8の畳縁の種類",
    need_amount: 20,
    deadline: Date.new(2016, 3, 20),
    estimated_sum: 30000,
  }
])

Comment.delete_all
Comment.create!([
  {
    id: 1,
    project_id: 1,
    company_id: 1,
    kind: 'general',
    body: "コメント1"
  },{
    id: 2,
    project_id: 1,
    company_id: 2,
    kind: 'general',
    body: "コメント2"
  },{
    id: 3,
    project_id: 1,
    company_id: 3,
    kind: 'request',
    status: '',
    body: "コメント3",
    amount: 12,
  },{
    id: 4,
    project_id: 1,
    company_id: 2,
    kind: 'request',
    status: 'ok',
    body: "コメント4",
    amount: 10,
  },{
    id: 5,
    project_id: 1,
    company_id: 1,
    kind: 'request',
    status: 'ng',
    body: "コメント5",
    amount: 10,
  },{
    id: 6,
    project_id: 1,
    company_id: 1,
    kind: 'request',
    status: '',
    body: "コメント6",
    amount: 10,
  },{
    id: 7,
    project_id: 2,
    company_id: 1,
    kind: 'general',
    body: "コメント7",
  },{
    id: 8,
    project_id: 2,
    company_id: 1,
    kind: 'general',
    body: "コメント8",
  },{
    id: 9,
    project_id: 4,
    company_id: 1,
    kind: 'request',
    status: 'ok',
    body: "コメント9",
    amount: 10,
  }
])


Commitment.delete_all
Commitment.create!([
  {
    id: 1,
    project_id: 1,
    source_company_id: 1,
    dest_company_id: 2,
    status: 'progress',
    body: '契約1',
    amount: 10,
  },{
    id: 2,
    project_id: 1,
    source_company_id: 1,
    dest_company_id: 3,
    status: 'done',
    body: '契約2',
    amount: 20,
  },{
    id: 3,
    project_id: 1,
    source_company_id: 1,
    dest_company_id: 4,
    status: 'done',
    body: '契約3',
    amount: 20,
  },{
    id: 4,
    project_id: 2,
    source_company_id: 1,
    dest_company_id: 3,
    status: 'done',
    body: '契約4',
    amount: 20,
  },{
    id: 5,
    project_id: 3,
    source_company_id: 3,
    dest_company_id: 1,
    status: 'done',
    body: '契約5',
    amount: 8,
  },{
    id: 6,
    project_id: 4,
    source_company_id: 3,
    dest_company_id: 1,
    status: 'progress',
    body: '契約6',
    amount: 8,
  }
])

Review.delete_all
Review.create!([
  {
    id: 1,
    commitment_id: 2,
    source_company_id: 3,
    dest_company_id: 1,
    body: 'レビュー1の本文',
    score1: 4,
    score2: 3,
    score3: 2,
    score4: 5,
    score5: 2,
  }, {
    id: 2,
    commitment_id: 3,
    source_company_id: 4,
    dest_company_id: 1,
    body: 'レビュー2の本文',
    score1: 4,
    score2: 5,
    score3: 5,
    score4: 4,
    score5: 4,
  }, {
    id: 3,
    commitment_id: 5,
    source_company_id: 1,
    dest_company_id: 4,
    body: 'レビュー3の本文',
    score1: 3,
    score2: 2,
    score3: 5,
    score4: 4,
    score5: 1,
  }
])
